// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "./gen-cpp/calculatorService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <iostream>
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;




int main(int argc, char **argv) {
  int port = 9090;

  ::std::shared_ptr<TSocket> socket(new TSocket("localhost" ,port));
  ::std::shared_ptr<TTransport> transport(new TBufferedTransport(socket));
  ::std::shared_ptr<TProtocol> protocol (new TBinaryProtocol(transport));
  calculatorServiceClient client(protocol);
  transport->open();
  int num1, num2, result;
  std::cout << "num1: ";
  std::cin >> num1;
  std::cout << "num2: ";
  std::cin >> num2;
  result = client.add(num1, num2);
  std::cout << "result: " << result << "\n"; 
  transport->close();
  return 0;

  return 0;
}

