// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "./gen-cpp/Serv.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <time.h>
#include <iostream>
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;


int main(int argc, char **argv) {
  
  int port = 9090;
  std::string ip = "localhost";
  // 10.10.1.1
  if (argc > 1) {
    ip = argc[1];
  }
  
  ::std::shared_ptr<TSocket> socket(new TSocket("localhost", port));
 
  ::std::shared_ptr<TTransport> transport(new TBufferedTransport(socket));
  ::std::shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
  std::string message = "Hello Server! sent from client";
  struct timespec start, end;
  ServClient client(protocol);
  transport->open();
  std::cout << "RoundTrip    Request    Response" << "\n";
  for (int i = 0; i < 20; ++i) {
  	
 	client.send(message);  
  	
  	
  }

  transport->close();
  

  return 0;
}

