/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Serv_H
#define Serv_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "packing_types.h"
#include <time.h>
#include <iostream>


#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ServIf {
 public:
  virtual ~ServIf() {}
  virtual int32_t intPacking(const int32_t num1) = 0;
  virtual double doublePacking(const double num2) = 0;
  virtual void stringPacking(std::string& _return, const std::string& str1) = 0;
  virtual void structPacking(heavy& _return, const heavy& h) = 0;
};

class ServIfFactory {
 public:
  typedef ServIf Handler;

  virtual ~ServIfFactory() {}

  virtual ServIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ServIf* /* handler */) = 0;
  };

class ServIfSingletonFactory : virtual public ServIfFactory {
 public:
  ServIfSingletonFactory(const ::std::shared_ptr<ServIf>& iface) : iface_(iface) {}
  virtual ~ServIfSingletonFactory() {}

  virtual ServIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(ServIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<ServIf> iface_;
};

class ServNull : virtual public ServIf {
 public:
  virtual ~ServNull() {}
  int32_t intPacking(const int32_t /* num1 */) override {
    int32_t _return = 0;
    return _return;
  }
  double doublePacking(const double /* num2 */) override {
    double _return = 0.0;
    return _return;
  }
  void stringPacking(std::string& /* _return */, const std::string& /* str1 */) override {
    return;
  }
  void structPacking(heavy& /* _return */, const heavy& /* h */) override {
    return;
  }
};

typedef struct _Serv_intPacking_args__isset {
  _Serv_intPacking_args__isset() : num1(false) {}
  bool num1 :1;
} _Serv_intPacking_args__isset;

class Serv_intPacking_args {
 public:

  Serv_intPacking_args(const Serv_intPacking_args&) noexcept;
  Serv_intPacking_args& operator=(const Serv_intPacking_args&) noexcept;
  Serv_intPacking_args() noexcept
                       : num1(0) {
  }

  virtual ~Serv_intPacking_args() noexcept;
  int32_t num1;

  _Serv_intPacking_args__isset __isset;

  void __set_num1(const int32_t val);

  bool operator == (const Serv_intPacking_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    return true;
  }
  bool operator != (const Serv_intPacking_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_intPacking_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_intPacking_pargs {
 public:


  virtual ~Serv_intPacking_pargs() noexcept;
  const int32_t* num1;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_intPacking_result__isset {
  _Serv_intPacking_result__isset() : success(false) {}
  bool success :1;
} _Serv_intPacking_result__isset;

class Serv_intPacking_result {
 public:

  Serv_intPacking_result(const Serv_intPacking_result&) noexcept;
  Serv_intPacking_result& operator=(const Serv_intPacking_result&) noexcept;
  Serv_intPacking_result() noexcept
                         : success(0) {
  }

  virtual ~Serv_intPacking_result() noexcept;
  int32_t success;

  _Serv_intPacking_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Serv_intPacking_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Serv_intPacking_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_intPacking_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_intPacking_presult__isset {
  _Serv_intPacking_presult__isset() : success(false) {}
  bool success :1;
} _Serv_intPacking_presult__isset;

class Serv_intPacking_presult {
 public:


  virtual ~Serv_intPacking_presult() noexcept;
  int32_t* success;

  _Serv_intPacking_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Serv_doublePacking_args__isset {
  _Serv_doublePacking_args__isset() : num2(false) {}
  bool num2 :1;
} _Serv_doublePacking_args__isset;

class Serv_doublePacking_args {
 public:

  Serv_doublePacking_args(const Serv_doublePacking_args&) noexcept;
  Serv_doublePacking_args& operator=(const Serv_doublePacking_args&) noexcept;
  Serv_doublePacking_args() noexcept
                          : num2(0) {
  }

  virtual ~Serv_doublePacking_args() noexcept;
  double num2;

  _Serv_doublePacking_args__isset __isset;

  void __set_num2(const double val);

  bool operator == (const Serv_doublePacking_args & rhs) const
  {
    if (!(num2 == rhs.num2))
      return false;
    return true;
  }
  bool operator != (const Serv_doublePacking_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_doublePacking_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_doublePacking_pargs {
 public:


  virtual ~Serv_doublePacking_pargs() noexcept;
  const double* num2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_doublePacking_result__isset {
  _Serv_doublePacking_result__isset() : success(false) {}
  bool success :1;
} _Serv_doublePacking_result__isset;

class Serv_doublePacking_result {
 public:

  Serv_doublePacking_result(const Serv_doublePacking_result&) noexcept;
  Serv_doublePacking_result& operator=(const Serv_doublePacking_result&) noexcept;
  Serv_doublePacking_result() noexcept
                            : success(0) {
  }

  virtual ~Serv_doublePacking_result() noexcept;
  double success;

  _Serv_doublePacking_result__isset __isset;

  void __set_success(const double val);

  bool operator == (const Serv_doublePacking_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Serv_doublePacking_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_doublePacking_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_doublePacking_presult__isset {
  _Serv_doublePacking_presult__isset() : success(false) {}
  bool success :1;
} _Serv_doublePacking_presult__isset;

class Serv_doublePacking_presult {
 public:


  virtual ~Serv_doublePacking_presult() noexcept;
  double* success;

  _Serv_doublePacking_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Serv_stringPacking_args__isset {
  _Serv_stringPacking_args__isset() : str1(false) {}
  bool str1 :1;
} _Serv_stringPacking_args__isset;

class Serv_stringPacking_args {
 public:

  Serv_stringPacking_args(const Serv_stringPacking_args&);
  Serv_stringPacking_args& operator=(const Serv_stringPacking_args&);
  Serv_stringPacking_args() noexcept
                          : str1() {
  }

  virtual ~Serv_stringPacking_args() noexcept;
  std::string str1;

  _Serv_stringPacking_args__isset __isset;

  void __set_str1(const std::string& val);

  bool operator == (const Serv_stringPacking_args & rhs) const
  {
    if (!(str1 == rhs.str1))
      return false;
    return true;
  }
  bool operator != (const Serv_stringPacking_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_stringPacking_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_stringPacking_pargs {
 public:


  virtual ~Serv_stringPacking_pargs() noexcept;
  const std::string* str1;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_stringPacking_result__isset {
  _Serv_stringPacking_result__isset() : success(false) {}
  bool success :1;
} _Serv_stringPacking_result__isset;

class Serv_stringPacking_result {
 public:

  Serv_stringPacking_result(const Serv_stringPacking_result&);
  Serv_stringPacking_result& operator=(const Serv_stringPacking_result&);
  Serv_stringPacking_result() noexcept
                            : success() {
  }

  virtual ~Serv_stringPacking_result() noexcept;
  std::string success;

  _Serv_stringPacking_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const Serv_stringPacking_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Serv_stringPacking_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_stringPacking_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_stringPacking_presult__isset {
  _Serv_stringPacking_presult__isset() : success(false) {}
  bool success :1;
} _Serv_stringPacking_presult__isset;

class Serv_stringPacking_presult {
 public:


  virtual ~Serv_stringPacking_presult() noexcept;
  std::string* success;

  _Serv_stringPacking_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Serv_structPacking_args__isset {
  _Serv_structPacking_args__isset() : h(false) {}
  bool h :1;
} _Serv_structPacking_args__isset;

class Serv_structPacking_args {
 public:

  Serv_structPacking_args(const Serv_structPacking_args&);
  Serv_structPacking_args& operator=(const Serv_structPacking_args&);
  Serv_structPacking_args() noexcept {
  }

  virtual ~Serv_structPacking_args() noexcept;
  heavy h;

  _Serv_structPacking_args__isset __isset;

  void __set_h(const heavy& val);

  bool operator == (const Serv_structPacking_args & rhs) const
  {
    if (!(h == rhs.h))
      return false;
    return true;
  }
  bool operator != (const Serv_structPacking_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_structPacking_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serv_structPacking_pargs {
 public:


  virtual ~Serv_structPacking_pargs() noexcept;
  const heavy* h;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_structPacking_result__isset {
  _Serv_structPacking_result__isset() : success(false) {}
  bool success :1;
} _Serv_structPacking_result__isset;

class Serv_structPacking_result {
 public:

  Serv_structPacking_result(const Serv_structPacking_result&);
  Serv_structPacking_result& operator=(const Serv_structPacking_result&);
  Serv_structPacking_result() noexcept {
  }

  virtual ~Serv_structPacking_result() noexcept;
  heavy success;

  _Serv_structPacking_result__isset __isset;

  void __set_success(const heavy& val);

  bool operator == (const Serv_structPacking_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Serv_structPacking_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serv_structPacking_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serv_structPacking_presult__isset {
  _Serv_structPacking_presult__isset() : success(false) {}
  bool success :1;
} _Serv_structPacking_presult__isset;

class Serv_structPacking_presult {
 public:


  virtual ~Serv_structPacking_presult() noexcept;
  heavy* success;

  _Serv_structPacking_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ServClient : virtual public ServIf {
 public:
  ServClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t intPacking(const int32_t num1) override;
  void send_intPacking(const int32_t num1);
  int32_t recv_intPacking();
  double doublePacking(const double num2) override;
  void send_doublePacking(const double num2);
  double recv_doublePacking();
  void stringPacking(std::string& _return, const std::string& str1) override;
  void send_stringPacking(const std::string& str1);
  void recv_stringPacking(std::string& _return);
  void structPacking(heavy& _return, const heavy& h) override;
  void send_structPacking(const heavy& h);
  void recv_structPacking(heavy& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ServProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<ServIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (ServProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_intPacking(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_doublePacking(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_stringPacking(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_structPacking(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ServProcessor(::std::shared_ptr<ServIf> iface) :
    iface_(iface) {
    processMap_["intPacking"] = &ServProcessor::process_intPacking;
    processMap_["doublePacking"] = &ServProcessor::process_doublePacking;
    processMap_["stringPacking"] = &ServProcessor::process_stringPacking;
    processMap_["structPacking"] = &ServProcessor::process_structPacking;
  }

  virtual ~ServProcessor() {}
};

class ServProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ServProcessorFactory(const ::std::shared_ptr< ServIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< ServIfFactory > handlerFactory_;
};

class ServMultiface : virtual public ServIf {
 public:
  ServMultiface(std::vector<std::shared_ptr<ServIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ServMultiface() {}
 protected:
  std::vector<std::shared_ptr<ServIf> > ifaces_;
  ServMultiface() {}
  void add(::std::shared_ptr<ServIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t intPacking(const int32_t num1) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->intPacking(num1);
    }
    return ifaces_[i]->intPacking(num1);
  }

  double doublePacking(const double num2) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->doublePacking(num2);
    }
    return ifaces_[i]->doublePacking(num2);
  }

  void stringPacking(std::string& _return, const std::string& str1) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->stringPacking(_return, str1);
    }
    ifaces_[i]->stringPacking(_return, str1);
    return;
  }

  void structPacking(heavy& _return, const heavy& h) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->structPacking(_return, h);
    }
    ifaces_[i]->structPacking(_return, h);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ServConcurrentClient : virtual public ServIf {
 public:
  ServConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  ServConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t intPacking(const int32_t num1) override;
  int32_t send_intPacking(const int32_t num1);
  int32_t recv_intPacking(const int32_t seqid);
  double doublePacking(const double num2) override;
  int32_t send_doublePacking(const double num2);
  double recv_doublePacking(const int32_t seqid);
  void stringPacking(std::string& _return, const std::string& str1) override;
  int32_t send_stringPacking(const std::string& str1);
  void recv_stringPacking(std::string& _return, const int32_t seqid);
  void structPacking(heavy& _return, const heavy& h) override;
  int32_t send_structPacking(const heavy& h);
  void recv_structPacking(heavy& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
