/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculatorService_H
#define calculatorService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "calculator_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class calculatorServiceIf {
 public:
  virtual ~calculatorServiceIf() {}
  virtual int32_t add(const int32_t num1, const int32_t num2) = 0;
};

class calculatorServiceIfFactory {
 public:
  typedef calculatorServiceIf Handler;

  virtual ~calculatorServiceIfFactory() {}

  virtual calculatorServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(calculatorServiceIf* /* handler */) = 0;
  };

class calculatorServiceIfSingletonFactory : virtual public calculatorServiceIfFactory {
 public:
  calculatorServiceIfSingletonFactory(const ::std::shared_ptr<calculatorServiceIf>& iface) : iface_(iface) {}
  virtual ~calculatorServiceIfSingletonFactory() {}

  virtual calculatorServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(calculatorServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<calculatorServiceIf> iface_;
};

class calculatorServiceNull : virtual public calculatorServiceIf {
 public:
  virtual ~calculatorServiceNull() {}
  int32_t add(const int32_t /* num1 */, const int32_t /* num2 */) override {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _calculatorService_add_args__isset {
  _calculatorService_add_args__isset() : num1(false), num2(false) {}
  bool num1 :1;
  bool num2 :1;
} _calculatorService_add_args__isset;

class calculatorService_add_args {
 public:

  calculatorService_add_args(const calculatorService_add_args&) noexcept;
  calculatorService_add_args& operator=(const calculatorService_add_args&) noexcept;
  calculatorService_add_args() noexcept
                             : num1(0),
                               num2(0) {
  }

  virtual ~calculatorService_add_args() noexcept;
  int32_t num1;
  int32_t num2;

  _calculatorService_add_args__isset __isset;

  void __set_num1(const int32_t val);

  void __set_num2(const int32_t val);

  bool operator == (const calculatorService_add_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    if (!(num2 == rhs.num2))
      return false;
    return true;
  }
  bool operator != (const calculatorService_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const calculatorService_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class calculatorService_add_pargs {
 public:


  virtual ~calculatorService_add_pargs() noexcept;
  const int32_t* num1;
  const int32_t* num2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _calculatorService_add_result__isset {
  _calculatorService_add_result__isset() : success(false) {}
  bool success :1;
} _calculatorService_add_result__isset;

class calculatorService_add_result {
 public:

  calculatorService_add_result(const calculatorService_add_result&) noexcept;
  calculatorService_add_result& operator=(const calculatorService_add_result&) noexcept;
  calculatorService_add_result() noexcept
                               : success(0) {
  }

  virtual ~calculatorService_add_result() noexcept;
  int32_t success;

  _calculatorService_add_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const calculatorService_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const calculatorService_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const calculatorService_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _calculatorService_add_presult__isset {
  _calculatorService_add_presult__isset() : success(false) {}
  bool success :1;
} _calculatorService_add_presult__isset;

class calculatorService_add_presult {
 public:


  virtual ~calculatorService_add_presult() noexcept;
  int32_t* success;

  _calculatorService_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class calculatorServiceClient : virtual public calculatorServiceIf {
 public:
  calculatorServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  calculatorServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add(const int32_t num1, const int32_t num2) override;
  void send_add(const int32_t num1, const int32_t num2);
  int32_t recv_add();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class calculatorServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<calculatorServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (calculatorServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  calculatorServiceProcessor(::std::shared_ptr<calculatorServiceIf> iface) :
    iface_(iface) {
    processMap_["add"] = &calculatorServiceProcessor::process_add;
  }

  virtual ~calculatorServiceProcessor() {}
};

class calculatorServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  calculatorServiceProcessorFactory(const ::std::shared_ptr< calculatorServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< calculatorServiceIfFactory > handlerFactory_;
};

class calculatorServiceMultiface : virtual public calculatorServiceIf {
 public:
  calculatorServiceMultiface(std::vector<std::shared_ptr<calculatorServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~calculatorServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<calculatorServiceIf> > ifaces_;
  calculatorServiceMultiface() {}
  void add(::std::shared_ptr<calculatorServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t add(const int32_t num1, const int32_t num2) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(num1, num2);
    }
    return ifaces_[i]->add(num1, num2);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class calculatorServiceConcurrentClient : virtual public calculatorServiceIf {
 public:
  calculatorServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  calculatorServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add(const int32_t num1, const int32_t num2) override;
  int32_t send_add(const int32_t num1, const int32_t num2);
  int32_t recv_add(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
